//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AM.EmergencyService.App.Data.AdServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdvertisingModel", Namespace="http://schemas.datacontract.org/2004/07/AM.EmergencyService.AdService.Model")]
    [System.SerializableAttribute()]
    public partial class AdvertisingModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdText {
            get {
                return this.AdTextField;
            }
            set {
                if ((object.ReferenceEquals(this.AdTextField, value) != true)) {
                    this.AdTextField = value;
                    this.RaisePropertyChanged("AdText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://AM.EmergencyService.AdService.Interface", ConfigurationName="AdServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://AM.EmergencyService.AdService.Interface/IService/GetAdvertising", ReplyAction="http://AM.EmergencyService.AdService.Interface/IService/GetAdvertisingResponse")]
        AM.EmergencyService.App.Data.AdServiceReference.AdvertisingModel[] GetAdvertising(int numberOfAd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://AM.EmergencyService.AdService.Interface/IService/GetAdvertising", ReplyAction="http://AM.EmergencyService.AdService.Interface/IService/GetAdvertisingResponse")]
        System.Threading.Tasks.Task<AM.EmergencyService.App.Data.AdServiceReference.AdvertisingModel[]> GetAdvertisingAsync(int numberOfAd);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : AM.EmergencyService.App.Data.AdServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<AM.EmergencyService.App.Data.AdServiceReference.IService>, AM.EmergencyService.App.Data.AdServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AM.EmergencyService.App.Data.AdServiceReference.AdvertisingModel[] GetAdvertising(int numberOfAd) {
            return base.Channel.GetAdvertising(numberOfAd);
        }
        
        public System.Threading.Tasks.Task<AM.EmergencyService.App.Data.AdServiceReference.AdvertisingModel[]> GetAdvertisingAsync(int numberOfAd) {
            return base.Channel.GetAdvertisingAsync(numberOfAd);
        }
    }
}
