INSERT INTO Brigades (BrigadeNumber)
VALUES ('101')
INSERT INTO Brigades (BrigadeNumber)
VALUES ('111')
INSERT INTO Brigades (BrigadeNumber)
VALUES ('121')
INSERT INTO Brigades (BrigadeNumber)
VALUES ('104')
INSERT INTO Brigades (BrigadeNumber)
VALUES ('114')
INSERT INTO Brigades (BrigadeNumber)
VALUES ('124')