INSERT INTO RescuersBrigade (IdBrigades, IdRescuers)
VALUES ('1', '1')
INSERT INTO RescuersBrigade (IdBrigades, IdRescuers)
VALUES ('2', '2')
INSERT INTO RescuersBrigade (IdBrigades, IdRescuers)
VALUES ('3', '3')
INSERT INTO RescuersBrigade (IdBrigades, IdRescuers)
VALUES ('4', '4')
INSERT INTO RescuersBrigade (IdBrigades, IdRescuers)
VALUES ('5', '5')
INSERT INTO RescuersBrigade (IdBrigades, IdRescuers)
VALUES ('6', '6')
INSERT INTO RescuersBrigade (IdBrigades, IdRescuers)
VALUES ('1', '7')
INSERT INTO RescuersBrigade (IdBrigades, IdRescuers)
VALUES ('2', '8')
INSERT INTO RescuersBrigade (IdBrigades, IdRescuers)
VALUES ('3', '9')
INSERT INTO RescuersBrigade (IdBrigades, IdRescuers)
VALUES ('4', '10')
INSERT INTO RescuersBrigade (IdBrigades, IdRescuers)
VALUES ('5', '11')
INSERT INTO RescuersBrigade (IdBrigades, IdRescuers)
VALUES ('6', '12')
INSERT INTO RescuersBrigade (IdBrigades, IdRescuers)
VALUES ('1', '13')
INSERT INTO RescuersBrigade (IdBrigades, IdRescuers)
VALUES ('1', '14')
INSERT INTO RescuersBrigade (IdBrigades, IdRescuers)
VALUES ('2', '15')
