INSERT INTO IncidentCasualty(IdIncident, IdCasualty)
VALUES ('14', '1')
INSERT INTO IncidentCasualty(IdIncident, IdCasualty)
VALUES ('14', '2')
INSERT INTO IncidentCasualty(IdIncident, IdCasualty)
VALUES ('14', '3')
INSERT INTO IncidentCasualty(IdIncident, IdCasualty)
VALUES ('14', '4')
INSERT INTO IncidentCasualty(IdIncident, IdCasualty)
VALUES ('14', '5')
INSERT INTO IncidentCasualty(IdIncident, IdCasualty)
VALUES ('15', '6')
INSERT INTO IncidentCasualty(IdIncident, IdCasualty)
VALUES ('15', '7')
INSERT INTO IncidentCasualty(IdIncident, IdCasualty)
VALUES ('15', '8')
INSERT INTO IncidentCasualty(IdIncident, IdCasualty)
VALUES ('15', '9')
INSERT INTO IncidentCasualty(IdIncident, IdCasualty)
VALUES ('16', '10')
INSERT INTO IncidentCasualty(IdIncident, IdCasualty)
VALUES ('16', '11')
INSERT INTO IncidentCasualty(IdIncident, IdCasualty)
VALUES ('16', '12')
INSERT INTO IncidentCasualty(IdIncident, IdCasualty)
VALUES ('16', '13')
INSERT INTO IncidentCasualty(IdIncident, IdCasualty)
VALUES ('16', '14')
INSERT INTO IncidentCasualty(IdIncident, IdCasualty)
VALUES ('16', '15')