INSERT INTO Inventory(InventoryNumber,InventoryName,IdBrigade)
VALUES ('12567894', 'Топор', 1)
INSERT INTO Inventory (InventoryNumber,InventoryName,IdBrigade)
VALUES ('65489324', 'Молоток', 1)
INSERT INTO Inventory (InventoryNumber,InventoryName,IdBrigade)
VALUES ('47895314', 'Топор', 2)
INSERT INTO Inventory (InventoryNumber,InventoryName,IdBrigade)
VALUES ('78464901', 'Багор', 2)
INSERT INTO Inventory (InventoryNumber,InventoryName,IdBrigade)
VALUES ('120348657', 'Шланг пожарный 50 м', 3)
INSERT INTO Inventory (InventoryNumber,InventoryName,IdBrigade)
VALUES ('489531020', 'Лазерный резак', 4)