INSERT INTO Casualty(Firstname,Surname,Lastname,BirthDate,Address)
VALUES ('Шкригунова', 'Берта', 'Олеговна','28/02/1956','ул. Баррикадная, дом 57, квартира 159')
INSERT INTO Casualty(Firstname,Surname,Lastname,BirthDate,Address)
VALUES ('Лагошина', 'Оксана', 'Брониславовна','09/02/1960','ул. Московская, дом 4, квартира 259')
INSERT INTO Casualty(Firstname,Surname,Lastname,BirthDate,Address)
VALUES ('Брантов', 'Гавриил', 'Фомевич','13/08/1960','ул. Барвихинская, дом 17, квартира 219')
INSERT INTO Casualty(Firstname,Surname,Lastname,BirthDate,Address)
VALUES ('Якшилов', 'Мирон', 'Прокофиевич','20/01/1962','ул. Деревцова, дом 25, квартира 192')
INSERT INTO Casualty(Firstname,Surname,Lastname,BirthDate,Address)
VALUES ('Янушковский', 'Карл', 'Матвеевич','27/12/1971','ул. Автозаводская, дом 33, квартира 95')
INSERT INTO Casualty(Firstname,Surname,Lastname,BirthDate,Address)
VALUES ('Праздников', 'Моисей', 'Назарович ','19/04/1988','ул. Маршала Конева, дом 94, квартира 262')
INSERT INTO Casualty(Firstname,Surname,Lastname,BirthDate,Address)
VALUES ('Торсунова', 'Наталия', 'Родионовна','08/01/1990','ул. Молодёжная, дом 93, квартира 143')
INSERT INTO Casualty(Firstname,Surname,Lastname,BirthDate,Address)
VALUES ('Широких', 'Аскольд', 'Якубович','23/06/2005','ул. Молодёжная, дом 90, квартира 6')
INSERT INTO Casualty(Firstname,Surname,Lastname,BirthDate,Address)
VALUES ('Шурдук', 'Кондратий', 'Леонович','13/11/2006','ул. Георгиевская, дом 19, квартира 187')
INSERT INTO Casualty(Firstname,Surname,Lastname,BirthDate,Address)
VALUES ('Жикина', 'Каролина', 'Станиславовна','16/02/2008','ул. Базовая, дом 52, квартира 95')
INSERT INTO Casualty(Firstname,Surname,Lastname,BirthDate,Address)
VALUES ('Эсаулова', 'Диана', 'Вячеславовна','02/05/2008','ул. Байдукова, дом 15, квартира 71')
INSERT INTO Casualty(Firstname,Surname,Lastname,BirthDate,Address)
VALUES ('Гурьянова', 'Владислава', 'Павеловна','08/08/2011','ул. Авиаконструктора Миля, дом 78, квартира 76')
INSERT INTO Casualty(Firstname,Surname,Lastname,BirthDate,Address)
VALUES ('Белова', 'Ангелина', 'Федотовна','20/08/2011','ул. Александра Завидова, дом 17, квартира 170')
INSERT INTO Casualty(Firstname,Surname,Lastname,BirthDate,Address)
VALUES ('Григорьева', 'Валентина', 'Глебовна','26/11/2012','ул. Театральная, дом 47, квартира 264')
INSERT INTO Casualty(Firstname,Surname,Lastname,BirthDate,Address)
VALUES ('Торсунова', 'Наталия', 'Родионовна','19/02/2016','ул. Баррикадная, дом 38, квартира 11')
INSERT INTO Casualty(Firstname,Surname,Lastname,BirthDate,Address)
VALUES ('Никитенко', 'Зинаида', 'Борисовна','19/01/1964','ул. Московская, дом 10, квартира 225')
