INSERT INTO Rescuers (Firstname,Surname,Lastname,BirthDate,Job)
VALUES ('Лапин', 'Эльдар','Валерьевич','19/01/1964','Бригадир')
INSERT INTO Rescuers (Firstname,Surname,Lastname,BirthDate,Job)
VALUES ('Суханов', 'Валентин','Иосифович','18/11/1975','Бригадир')
INSERT INTO Rescuers (Firstname,Surname,Lastname,BirthDate,Job)
VALUES ('Русаков', 'Ибрагил', 'Яковлевич','27/07/1976','Бригадир')
INSERT INTO Rescuers (Firstname,Surname,Lastname,BirthDate,Job)
VALUES ('Дроздов', 'Донат', 'Христофорович','09/10/1978','Бригадир')
INSERT INTO Rescuers (Firstname,Surname,Lastname,BirthDate,Job)
VALUES ('Игнатьев', 'Аполлон', 'Филиппович','15/03/1979','Бригадир')
INSERT INTO Rescuers (Firstname,Surname,Lastname,BirthDate,Job)
VALUES ('Константинов', 'Рудольф', 'Тимурович','26/10/1982','Бригадир')
INSERT INTO Rescuers (Firstname,Surname,Lastname,BirthDate,Job)
VALUES ('Денисов', 'Натан', 'Матвеевич','23/01/1985','Инженер-спасатель')
INSERT INTO Rescuers (Firstname,Surname,Lastname,BirthDate,Job)
VALUES ('Копылов', 'Натан', 'Донатович','23/09/1986','Инженер-спасатель')
INSERT INTO Rescuers (Firstname,Surname,Lastname,BirthDate,Job)
VALUES ('Муравьёв', 'Карл', 'Глебович','22/03/1988','Инженер-спасатель')
INSERT INTO Rescuers (Firstname,Surname,Lastname,BirthDate,Job)
VALUES ('Колобов', 'Ефим', 'Вячеславович','20/04/1990','Инженер-спасатель')
INSERT INTO Rescuers (Firstname,Surname,Lastname,BirthDate,Job)
VALUES ('Никифоров', 'Климент', 'Степанович','03/02/1991','Инженер-спасатель')
INSERT INTO Rescuers (Firstname,Surname,Lastname,BirthDate,Job)
VALUES ('Горшков', 'Панкрат', 'Филатович','13/12/1992','Инженер-спасатель')
INSERT INTO Rescuers (Firstname,Surname,Lastname,BirthDate,Job)
VALUES ('Назаров', 'Касьян', 'Макарович', '19/01/1964','Реаниматор')
INSERT INTO Rescuers (Firstname,Surname,Lastname,BirthDate,Job)
VALUES ('Ситников', 'Олег', 'Онисимович','08/02/1994','Водитель')
INSERT INTO Rescuers (Firstname,Surname,Lastname,BirthDate,Job)
VALUES ('Цветков', 'Велорий', 'Витальевич','01/08/1995','Водитель')
